'use strict';
// All requests stay on a disposable localhost server with a mocked uibuilder.
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');
const root=path.join(__dirname,'../src');
const mock=`window.sent=[];const listeners={};window.uibuilder={ioConnected:false,onChange:(k,f)=>(listeners[k]??=[]).push(f),send:m=>sent.push(m)};window.emit=m=>(listeners.msg||[]).forEach(f=>f(m));window.connect=on=>{uibuilder.ioConnected=on;(listeners.ioConnected||[]).forEach(f=>f(on))};`;
const server=http.createServer((req,res)=>{if(req.url.includes('uibuilder.iife')){res.setHeader('Content-Type','text/javascript');res.end(mock);return;}const file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(root)){res.writeHead(403);res.end();return;}try{const type=file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':file.endsWith('.svg')?'image/svg+xml':'application/octet-stream';res.setHeader('Content-Type',type);res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true,channel:process.env.TEST_BROWSER_CHANNEL || 'msedge'});const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.evaluate(()=>{connect(true);emit({topic:'status',payload:'idle'});emit({topic:'poi',payload:'LM1'});emit({topic:'battery',payload:{battery_pct:83,charging:false}});emit({topic:'robotName',payload:'SITE-AMR'});emit({topic:'fleet/job-progress',payload:{active:false}});});
assert.equal(await page.locator('[data-robot-name]').first().textContent(),'SITE-AMR');
await page.evaluate(()=>{emit({topic:'nav/progress',payload:{target:'LM2',mode:'suspended',is_suspended:true}});});
assert.equal(await page.evaluate(()=>AMRStore.getState().navigation.state),'paused');
await page.evaluate(()=>{emit({topic:'nav/cancelled',payload:{target:'LM2',poi:'LM2'}});});
assert.equal(await page.evaluate(()=>AMRStore.getState().robot.currentPoi),'LM1');
await page.evaluate(()=>{emit({topic:'wait/start',payload:{waitId:'w1',title:'Load Material',indefinite:true}});});
assert(await page.locator('.workflow-dialog').evaluate(el=>el.open));
await page.locator('#workflowReady').click();assert.equal(await page.evaluate(()=>sent.at(-1).payload.waitId),'w1');
await page.evaluate(()=>{emit({topic:'wait/done',payload:{waitId:'w1'}});});assert.equal(await page.locator('.workflow-dialog').evaluate(el=>el.open),false);
await page.evaluate(()=>{emit({topic:'config/pages',payload:[{id:'A',title:'Select Material',selectTopic:'enqueue',destinations:[{point:'JOB-A',label:'Material A'}]}]});emit({topic:'ui/page',payload:{page:'A'}});});
assert.equal(await page.locator('#workflowChoices button').textContent(),'Material A');
await page.locator('#workflowChoices button').click();await page.locator('#dialogConfirm').click();await page.waitForFunction(()=>sent.some(m=>m.topic==='enqueue'));assert.equal(await page.evaluate(()=>sent.findLast(m=>m.topic==='enqueue').payload.point),'JOB-A');
await page.evaluate(()=>{emit({topic:'enqueue/success',payload:{}});emit({topic:'battery',payload:{battery_pct:83,charging:true}});});
assert((await page.locator('.live-banner').textContent()).includes('charging'));
await page.evaluate(()=>{emit({topic:'battery',payload:{battery_pct:83,charging:false}});connect(false);});
assert.equal(await page.locator('#resumeButton').isDisabled(),true);
await page.evaluate(()=>{connect(true);emit({topic:'status',payload:'idle'});emit({topic:'ui/settings/state',payload:{revision:0,config:{standbyPoint:'LM1',chargingPoint:'CP1',visiblePoints:[]}}});setView('settings');AMRSettings.refresh();emit({topic:'poi/stations',payload:{points:[{id:'LM1',name:'Lobby'},{id:'CP1',name:'Charger'}]}});});
await page.locator('[data-config="points"]').click();
await page.locator('input[name="point"][value="LM1"]').check();await page.locator('input[name="label_LM1"]').fill('Reception');
await page.locator('#reloadPoints').click();await page.evaluate(()=>emit({topic:'poi/stations',payload:{points:[{id:'LM1',name:'Lobby'},{id:'CP1',name:'Charger'}]}}));
assert.equal(await page.locator('input[name="label_LM1"]').inputValue(),'Reception');assert(await page.locator('input[name="point"][value="LM1"]').isChecked());
await page.locator('#configForm button[value="default"]').click();await page.waitForFunction(()=>sent.some(m=>m.topic==='ui/settings/save'));
assert.equal(await page.evaluate(()=>sent.findLast(m=>m.topic==='ui/settings/save').payload.values.points[0].label),'Reception');
await page.evaluate(()=>{const m=sent.findLast(m=>m.topic==='ui/settings/save');emit({topic:'ui/settings/saved',payload:{request_id:m.payload.request_id,revision:1,config:{standbyPoint:'LM1',chargingPoint:'CP1',visiblePoints:m.payload.values.points}}});});
assert.equal(await page.locator('#configDialog').evaluate(el=>el.open),false);
await page.evaluate(()=>{emit({topic:'wait/start',payload:{waitId:'w2',title:'Confirm Material Loaded',detail:'Press Ready when loading is complete.',indefinite:true}});});
assert((await page.locator('#workflowCountdown').textContent()).includes('no automatic timeout'));
await page.evaluate(()=>{emit({topic:'wait/start',payload:{waitId:'timed',target:'LM9',seconds:30,deadlineAt:new Date(Date.now()+30000).toISOString()}});});
assert((await page.locator('#workflowCountdown').textContent()).includes('automatically in'));
assert((await page.locator('#workflowMeta').textContent()).includes('LM9'));
await page.evaluate(()=>{emit({topic:'wait/done',payload:{waitId:'w2'}});});assert(await page.locator('.workflow-dialog').evaluate(el=>el.open));
await page.evaluate(()=>{emit({topic:'wait/start',payload:{waitId:'timed',seconds:30,deadlineAt:new Date(Date.now()-1000).toISOString()}});});
assert((await page.locator('#workflowCountdown').textContent()).includes('Maximum wait reached'));
assert.equal(await page.evaluate(()=>sent.filter(m=>m.topic==='wait/control/ready'&&m.payload.auto).length),0);
await page.evaluate(()=>{emit({topic:'robot/error',payload:{has_error:true,errors:[{code:52100}]}});});
assert((await page.locator('#robotAlertList').textContent()).includes('laser error'));
assert(await page.locator('.robot-alert-panel').evaluate(el=>el.matches(':popover-open')));
assert(await page.locator('.workflow-dialog').evaluate(el=>el.open));
await page.evaluate(()=>{window.speechCount=0;window.speechSynthesis.speak=()=>speechCount++;window.speechSynthesis.cancel=()=>{};});
await page.locator('#robotAlertVoice').click();assert.equal(await page.evaluate(()=>speechCount),1);
await page.evaluate(()=>emit({topic:'robot/error',payload:{has_error:true,errors:[{code:52100}]}}));assert.equal(await page.evaluate(()=>speechCount),1);
await page.evaluate(()=>emit({topic:'robot/error',payload:{has_error:true,errors:[{code:99999,desc:'Controller detail'}]}}));assert.equal(await page.evaluate(()=>speechCount),2);
await page.evaluate(()=>emit({topic:'robot/error',payload:{has_error:false,errors:[],fatals:[],warnings:[]}}));assert.equal(await page.locator('.robot-alert-panel').evaluate(el=>el.matches(':popover-open')),false);
assert(await page.locator('.workflow-dialog').evaluate(el=>el.open));
await page.evaluate(()=>{emit({topic:'wait/done',payload:{waitId:'timed',auto:true}});emit({topic:'nav/progress',payload:{mode:'running',target:'LM20'}});emit({topic:'destination',payload:[1,2,3]});});
assert.equal(await page.locator('#movingTitle').textContent(),'Destination: LM20');
await page.evaluate(()=>emit({topic:'robot/error',payload:{has_error:true,errors:[{code:52100}]}}));
if(process.env.TEST_SCREENSHOT)await page.screenshot({path:process.env.TEST_SCREENSHOT});
await page.evaluate(()=>{emit({topic:'robot/error',payload:{has_error:false,errors:[],fatals:[],warnings:[]}});emit({topic:'status',payload:'idle'});emit({topic:'fleet/job-progress',payload:{active:false}});emit({topic:'poi/stations',payload:{points:[{id:'LM1',name:'Lobby',x:1.5,y:2.5,r:0.7},{id:'CP1',name:'Charger',x:4,y:5,r:0}]}});});
await page.locator('#maintenanceOpen').click();
await page.locator('#relocatePoint').selectOption('LM1');await page.locator('#relocateGo').click();await page.locator('#dialogConfirm').click();
await page.waitForFunction(()=>sent.some(m=>m.topic==='relocate'));
let maintenance=await page.evaluate(()=>sent.findLast(m=>m.topic==='relocate'));
assert.deepEqual({x:maintenance.payload.x,y:maintenance.payload.y,angle:maintenance.payload.angle},{x:1.5,y:2.5,angle:0.7});
await page.evaluate(()=>{const m=sent.findLast(x=>x.topic==='relocate');emit({topic:'relocate/success',payload:{poi:'LM1'},_maintenanceRequestId:m.payload.request_id});});
assert((await page.locator('#maintenanceFeedback').textContent()).includes('acknowledged'));
await page.locator('#soundFile').fill('alert.wav');await page.locator('[data-sound="play_audio"]').click();await page.waitForFunction(()=>sent.some(m=>m.topic==='sound'));
maintenance=await page.evaluate(()=>sent.findLast(m=>m.topic==='sound'));assert.equal(maintenance.payload.name,'alert.wav');
await page.evaluate(()=>{const m=sent.findLast(x=>x.topic==='sound');emit({topic:'sound/ack',payload:{accepted:true},_maintenanceRequestId:m.payload.request_id});});
await page.locator('#hookOn').click();await page.locator('#dialogConfirm').click();await page.waitForFunction(()=>sent.some(m=>m.topic==='do_control'));
maintenance=await page.evaluate(()=>sent.findLast(m=>m.topic==='do_control'));assert.equal(maintenance.payload.point,'HOOK');assert.equal(maintenance.payload.state,true);
await page.evaluate(()=>{const m=sent.findLast(x=>x.topic==='do_control');emit({topic:'do_status',payload:{point:'HOOK',accepted:true},_maintenanceRequestId:m.payload.request_id});emit({topic:'do_status',payload:{point:'HOOK',state:true}});});
assert((await page.locator('#hookState').textContent()).includes('ON'));
await page.locator('#maintenanceClose').click();
await page.evaluate(()=>{emit({topic:'nav/progress',payload:{target:'CP1',mode:'running'}});});
await page.locator('#chargingDetails').click();assert.equal(await page.locator('#chargingPhase').textContent(),'Going to Charger');
await page.evaluate(()=>{emit({topic:'nav/arrived',payload:{poi:'CP1'}});emit({topic:'poi',payload:'CP1'});});assert.equal(await page.locator('#chargingPhase').textContent(),'Waiting for Charging');
await page.evaluate(()=>emit({topic:'battery',payload:{battery_pct:62,charging:true}}));assert.equal(await page.locator('#chargingPhase').textContent(),'Charging');assert.equal(await page.locator('#chargingLevel').textContent(),'62%');
await page.evaluate(()=>emit({topic:'battery',payload:{battery_pct:63,charging:false}}));assert.equal(await page.locator('#chargingPhase').textContent(),'Charging Stopped');
assert.deepEqual(errors,[]); console.log('Browser regression: core workflow, settings draft, maintenance commands, charging phases and alerts passed');
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
