'use strict';
// All requests stay on a disposable localhost server with a mocked uibuilder.
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');
const root=path.join(__dirname,'../src');
const mock=`window.sent=[];const listeners={};window.uibuilder={ioConnected:false,onChange:(k,f)=>(listeners[k]??=[]).push(f),send:m=>sent.push(m)};window.emit=m=>(listeners.msg||[]).forEach(f=>f(m));window.connect=on=>{uibuilder.ioConnected=on;(listeners.ioConnected||[]).forEach(f=>f(on))};`;
const server=http.createServer((req,res)=>{if(req.url.includes('uibuilder.iife')){res.setHeader('Content-Type','text/javascript');res.end(mock);return;}const file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(root)){res.writeHead(403);res.end();return;}try{const type=file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':file.endsWith('.svg')?'image/svg+xml':'application/octet-stream';res.setHeader('Content-Type',type);res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true,channel:process.env.TEST_BROWSER_CHANNEL || 'msedge'});const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.evaluate(()=>{connect(true);emit({topic:'status',payload:'idle'});emit({topic:'poi',payload:'LM1'});emit({topic:'battery',payload:{battery_pct:83,charging:false}});emit({topic:'robotName',payload:'SITE-AMR'});emit({topic:'fleet/job-progress',payload:{active:false}});});
assert.equal(await page.locator('[data-robot-name]').first().textContent(),'SITE-AMR');
await page.evaluate(()=>{emit({topic:'nav/progress',payload:{target:'LM2',mode:'suspended',is_suspended:true}});});
assert.equal(await page.evaluate(()=>AMRStore.getState().navigation.state),'paused');
await page.evaluate(()=>{emit({topic:'nav/cancelled',payload:{target:'LM2',poi:'LM2'}});});
assert.equal(await page.evaluate(()=>AMRStore.getState().robot.currentPoi),'LM1');
await page.evaluate(()=>{emit({topic:'wait/start',payload:{waitId:'w1',title:'Load Material',indefinite:true}});});
assert(await page.locator('.workflow-dialog').evaluate(el=>el.open));
await page.locator('#workflowReady').click();assert.equal(await page.evaluate(()=>sent.at(-1).payload.waitId),'w1');
await page.evaluate(()=>{emit({topic:'wait/done',payload:{waitId:'w1'}});});assert.equal(await page.locator('.workflow-dialog').evaluate(el=>el.open),false);
await page.evaluate(()=>{emit({topic:'config/pages',payload:[{id:'A',title:'Select Material',selectTopic:'enqueue',destinations:[{point:'JOB-A',label:'Material A'}]}]});emit({topic:'ui/page',payload:{page:'A'}});});
assert.equal(await page.locator('#workflowChoices button').textContent(),'Material A');
await page.locator('#workflowChoices button').click();await page.locator('#dialogConfirm').click();await page.waitForFunction(()=>sent.some(m=>m.topic==='enqueue'));assert.equal(await page.evaluate(()=>sent.findLast(m=>m.topic==='enqueue').payload.point),'JOB-A');
await page.evaluate(()=>{emit({topic:'enqueue/success',payload:{}});emit({topic:'battery',payload:{battery_pct:83,charging:true}});});
assert((await page.locator('.live-banner').textContent()).includes('charging'));
await page.evaluate(()=>{emit({topic:'battery',payload:{battery_pct:83,charging:false}});connect(false);});
assert.equal(await page.locator('#resumeButton').isDisabled(),true);
await page.evaluate(()=>{connect(true);emit({topic:'status',payload:'idle'});emit({topic:'ui/settings/state',payload:{revision:0,config:{standbyPoint:'LM1',chargingPoint:'CP1',visiblePoints:[]}}});setView('settings');AMRSettings.refresh();emit({topic:'poi/stations',payload:{points:[{id:'LM1',name:'Lobby'},{id:'CP1',name:'Charger'}]}});});
await page.locator('[data-config="points"]').click();
await page.locator('input[name="point"][value="LM1"]').check();await page.locator('input[name="label_LM1"]').fill('Reception');
await page.locator('#reloadPoints').click();await page.evaluate(()=>emit({topic:'poi/stations',payload:{points:[{id:'LM1',name:'Lobby'},{id:'CP1',name:'Charger'}]}}));
assert.equal(await page.locator('input[name="label_LM1"]').inputValue(),'Reception');assert(await page.locator('input[name="point"][value="LM1"]').isChecked());
await page.locator('#configForm button[value="default"]').click();await page.waitForFunction(()=>sent.some(m=>m.topic==='ui/settings/save'));
assert.equal(await page.evaluate(()=>sent.findLast(m=>m.topic==='ui/settings/save').payload.values.points[0].label),'Reception');
await page.evaluate(()=>{const m=sent.findLast(m=>m.topic==='ui/settings/save');emit({topic:'ui/settings/saved',payload:{request_id:m.payload.request_id,revision:1,config:{standbyPoint:'LM1',chargingPoint:'CP1',visiblePoints:m.payload.values.points}}});});
assert.equal(await page.locator('#configDialog').evaluate(el=>el.open),false);
await page.evaluate(()=>{emit({topic:'wait/start',payload:{waitId:'w2',title:'Confirm Material Loaded',detail:'Press Ready when loading is complete.',indefinite:true}});});
if(process.env.TEST_SCREENSHOT)await page.screenshot({path:process.env.TEST_SCREENSHOT});
assert.deepEqual(errors,[]); console.log('Browser regression: telemetry, pause, cancel location, wait confirmation, dynamic enqueue, charging and disconnect passed');
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
