const state={view:'home',taskSource:'Point-to-Point Move',from:'LM45',to:'LM47',fleetOnline:true,battery:76};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function setView(name){state.view=name;$$('.view').forEach(v=>v.classList.remove('is-active'));$('#'+name+'View').classList.add('is-active');$('#app').dataset.view=name}
function tickClock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false})}tickClock();setInterval(tickClock,1000);
function sendEdge(action,params={}){const message={topic:'edge/command/request',payload:{request_id:'ui-'+Date.now().toString(36),action,params,created_at:new Date().toISOString()}};if(window.uibuilder?.send)window.uibuilder.send(message);else console.info('[V2 demo]',message);return message.payload.request_id}
function startMove(source,target){state.taskSource=source;state.to=target;$('#movingTitle').textContent='Moving to '+target;$('#pausedTaskName').textContent=source;$('#pausedAction').textContent='Go to '+target;$('#pausedFrom').textContent=state.from;$('#pausedTo').textContent=target;$('#taskTitle').textContent=source;$('#taskDetail').textContent='Moving to '+target;$('#taskBadge').textContent='RUNNING';$('#robotMode').textContent='Moving';$('#taskRoute').hidden=false;$('#routeFrom').textContent=state.from;$('#routeTo').textContent=target;sendEdge('navigate',{source,target});setView('moving')}
function confirmAction(title,text,confirmText,onConfirm){const d=$('#confirmDialog');$('#dialogTitle').textContent=title;$('#dialogText').textContent=text;$('#dialogConfirm').textContent=confirmText;d.returnValue='';d.showModal();d.addEventListener('close',function done(){d.removeEventListener('close',done);if(d.returnValue==='confirm')onConfirm()})}
$$('[data-action]').forEach(button=>button.addEventListener('click',()=>{const a=button.dataset.action;if(a==='device')return $('#infoDialog').showModal();if(a==='settings'){ $('#settingsPassword').value='';$('#passwordError').textContent='';return $('#settingsDialog').showModal()}if(a==='fleet')return openFleetTasks();if(a==='point')return confirmAction('Go to Point','Navigate to approved destination LM47.','Start Move',()=>startMove('Point-to-Point Move','LM47'));if(a==='charge')return confirmAction('Go to Charger','Robot will navigate to default charger CP1.','Go Charge',()=>startMove('Charging Run','CP1'));if(a==='standby')return confirmAction('Return to Standby','Robot will return to standby point HR775.','Return',()=>startMove('Standby Return','HR775'))}));
$('#movingTouchArea').addEventListener('pointerup',()=>{sendEdge('pause',{target:state.to});setView('paused')});
$('#resumeButton').addEventListener('click',()=>{sendEdge('resume',{target:state.to});setView('moving')});
$('#cancelButton').addEventListener('click',()=>confirmAction('Cancel Current Task?','Robot will stop the current navigation.\nTask: '+state.taskSource+'\nDestination: '+state.to,'Confirm Cancel',()=>{sendEdge('cancel',{target:state.to});$('#taskTitle').textContent='No Active Task';$('#taskDetail').textContent='Robot is ready to accept a new task';$('#taskBadge').textContent='READY';$('#taskRoute').hidden=true;$('#robotMode').textContent='Idle';setView('home')}));
$('#togglePassword').addEventListener('click',()=>{const i=$('#settingsPassword');i.type=i.type==='password'?'text':'password';$('#togglePassword').textContent=i.type==='password'?'Show':'Hide'});
$('#passwordForm').addEventListener('submit',event=>{event.preventDefault();if($('#settingsPassword').value!=='admin_amr'){ $('#passwordError').textContent='Incorrect password. Please try again.';$('#settingsPassword').select();return}$('#settingsDialog').close();setView('settings')});
$('#closeSettings').addEventListener('click',()=>setView('home'));
const configDefinitions={
fleet:{title:'Fleet Task Configuration',description:'Choose the Fleet task operators can start from the home screen.',fields:'<div class="config-field"><label for="fleetTask">FLEET TASK</label><select id="fleetTask" name="fleetTask"><option value="standard-cleaning">Standard Cleaning</option><option value="deep-cleaning">Deep Cleaning</option><option value="inspection">Inspection Route</option></select></div><div class="config-field"><label for="fleetLabel">OPERATOR LABEL</label><input id="fleetLabel" name="fleetLabel" value="Fleet Tasks"></div>'},
standby:{title:'Standby Point',description:'Set the default destination used by Return to Standby.',fields:'<div class="config-field"><label for="standbyPoint">POINT</label><select id="standbyPoint" name="standbyPoint"><option>HR775</option><option>LM45</option><option>ST01</option></select></div><div class="config-field"><label for="standbyLabel">OPERATOR LABEL</label><input id="standbyLabel" name="standbyLabel" value="Main Standby"></div>'},
charge:{title:'Charging Point',description:'Set the charging destination used by Go Charge.',fields:'<div class="config-field"><label for="chargePoint">POINT</label><select id="chargePoint" name="chargePoint"><option>CP1</option><option>CP2</option></select></div><div class="config-field"><label for="chargeLabel">OPERATOR LABEL</label><input id="chargeLabel" name="chargeLabel" value="Main Charger"></div>'},
points:{title:'Visible Points',description:'Only selected points and their operator labels appear in Go to Point.',fields:'<div class="point-row"><input type="checkbox" name="point" value="LM47" checked><strong>LM47</strong><input type="text" value="Main Lobby" aria-label="LM47 operator label"></div><div class="point-row"><input type="checkbox" name="point" value="LM52" checked><strong>LM52</strong><input type="text" value="East Corridor" aria-label="LM52 operator label"></div><div class="point-row"><input type="checkbox" name="point" value="HR775" checked><strong>HR775</strong><input type="text" value="Service Area" aria-label="HR775 operator label"></div><div class="point-row"><input type="checkbox" name="point" value="ST01" checked><strong>ST01</strong><input type="text" value="Storage Room" aria-label="ST01 operator label"></div>'}
};
$$('[data-config]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.config;const config=configDefinitions[key];const dialog=$('#configDialog');dialog.dataset.config=key;$('#configTitle').textContent=config.title;$('#configDescription').textContent=config.description;$('#configFields').innerHTML=config.fields;$('#configFeedback').textContent='';dialog.showModal()}));
$('#configForm').addEventListener('submit',event=>{event.preventDefault();const dialog=$('#configDialog');sendEdge('settings/save',{section:dialog.dataset.config});$('#configFeedback').textContent='Settings saved';setTimeout(()=>dialog.close(),550)});
if(window.uibuilder&&typeof window.uibuilder.onChange==='function')window.uibuilder.onChange('msg',msg=>{if(window.handleFleetMessage)window.handleFleetMessage(msg)});
