(function(){
  'use strict';
  const store=window.AMRStore,transport=window.AMRTransport,$=s=>document.querySelector(s);
  let charging=null,chargeAt=0,wasCharging=false,seenCharging=false,lastNavTarget='',pending=null;
  const diagnostic=new Map();
  const charge=document.createElement('section');charge.id='chargingView';charge.className='view equipment-view';
  charge.innerHTML='<header><h1>Charging</h1><button class="secondary" id="chargeBack">Home</button></header><article><span class="panel-kicker">CHARGING STATUS</span><h2 id="chargingPhase">Checking status</h2><strong class="charge-level" id="chargingLevel">—</strong><dl><dt>Charger</dt><dd id="chargingPoint">—</dd><dt>Current Location</dt><dd id="chargingLocation">—</dd><dt>Last Feedback</dt><dd id="chargingUpdated">—</dd></dl><p>Arrival at the charging point does not confirm charging.</p></article>';
  $('#app').append(charge);$('#chargeBack').onclick=()=>window.setView('home');
  const chargeEntry=document.createElement('button');chargeEntry.className='secondary';chargeEntry.textContent='Charging Details';chargeEntry.id='chargingDetails';chargeEntry.onclick=()=>{renderCharge();window.setView('charging');};$('#infoDialog form').append(chargeEntry);chargeEntry.onclick=()=>{$('#infoDialog').close();renderCharge();window.setView('charging');};
  const maintenance=document.createElement('dialog');maintenance.className='dialog maintenance-dialog';maintenance.id='maintenanceDialog';
  maintenance.innerHTML='<h2>Maintenance</h2><p>Local robot controls. Confirm the robot is stationary before operating equipment.</p><section><h3>Relocalization</h3><button id="maintenancePoints" class="secondary">Reload Points</button><select id="relocatePoint" aria-label="Physical robot location"></select><button id="relocateGo" class="primary">Relocalize at Point</button></section><section><h3>Robot Sound</h3><input id="soundFile" placeholder="Audio file on robot, e.g. alert.wav"><div id="soundButtons"></div></section><section><h3>Hook / Digital Output</h3><p id="hookState">Physical state: Unknown</p><button id="hookOn" class="secondary">Hook ON</button><button id="hookOff" class="secondary">Hook OFF</button><small>Only HOOK is mapped in the current flow. A command acknowledgement does not confirm its physical position.</small></section><p id="maintenanceFeedback" role="status"></p><button id="maintenanceClose" class="secondary">Close</button>';
  document.body.append(maintenance);
  const entry=document.createElement('button');entry.className='secondary';entry.textContent='Maintenance';entry.id='maintenanceOpen';$('.settings-header').append(entry);
  entry.onclick=()=>{maintenance.showModal();populatePoints();};$('#maintenanceClose').onclick=()=>maintenance.close();
  $('#maintenancePoints').onclick=()=>{window.AMRSettings.refresh();$('#maintenanceFeedback').textContent='Loading current map points…';};
  function populatePoints(){const select=$('#relocatePoint'),selected=select.value;select.replaceChildren();for(const point of window.AMRSettings.getCatalog()){const opt=document.createElement('option');opt.value=point.id;opt.textContent=point.name?point.id+' — '+point.name:point.id;select.append(opt);}if([...select.options].some(o=>o.value===selected))select.value=selected;}
  function available(){return transport.getStatus()==='online' && window.AMRWorkflow.canNavigate() && !pending;}
  function command(topic,payload){if(!available()){$('#maintenanceFeedback').textContent='Unavailable: robot must be idle, connected and free of active tasks/errors.';return;}const request_id=transport.requestId('maintenance');const result=transport.send(topic,{...payload,request_id});if(result.sent){pending={topic,id:request_id,at:Date.now()};$('#maintenanceFeedback').textContent='Request sent — waiting for acknowledgement.';}renderMaintenance();}
  $('#relocateGo').onclick=()=>{const point=window.AMRSettings.getCatalog().find(p=>p.id===$('#relocatePoint').value);if(!point)return;const x=Number(point.x),y=Number(point.y),angle=Number(point.r ?? point.angle ?? 0);if(point.x==null||point.y==null||![x,y,angle].every(Number.isFinite)){$('#maintenanceFeedback').textContent='This point has no valid map coordinates. Reload the map.';return;}window.confirmAction('Confirm Physical Location','Confirm the robot is physically at '+point.id+'. This resets localization; it does not navigate.', 'Relocalize',()=>command('relocate',{isAuto:false,poi:point.id,poiName:point.name || point.id,x,y,angle}));};
  for(const [action,label] of [['play_audio','Play'],['pause_audio','Pause'],['resume_audio','Resume'],['stop_audio','Stop']]){const b=document.createElement('button');b.className='secondary';b.textContent=label;b.dataset.sound=action;b.onclick=()=>{const name=$('#soundFile').value.trim();if(action==='play_audio'&&!name){$('#maintenanceFeedback').textContent='Enter an audio filename.';return;}command('sound',{action,name});};$('#soundButtons').append(b);}
  for(const [id,state] of [['hookOn',true],['hookOff',false]])$('#'+id).onclick=()=>window.confirmAction(state?'Turn Hook ON?':'Turn Hook OFF?','Confirm equipment is clear to operate.', 'Confirm',()=>command('do_control',{point:'HOOK',state}));
  function renderMaintenance(){maintenance.querySelectorAll('#relocateGo,#hookOn,#hookOff,[data-sound]').forEach(b=>b.disabled=!available());}
  function renderCharge(){const s=store.getState(),target=s.config.chargingPoint;let phase='Not charging';if(!chargeAt||Date.now()-chargeAt>20000)phase='Charging status unavailable';else if(charging===true)phase='Charging';else if(target&&s.navigation.destination===target&&['running','waiting','submitting'].includes(s.navigation.state))phase='Going to Charger';else if(target&&s.robot.currentPoi===target&&lastNavTarget===target)phase='Waiting for Charging';else if(wasCharging)phase='Charging Stopped';$('#chargingPhase').textContent=phase;$('#chargingLevel').textContent=s.robot.battery==null?'—':Math.round(s.robot.battery)+'%';$('#chargingPoint').textContent=target || 'Not configured';$('#chargingLocation').textContent=s.robot.currentPoi || '—';$('#chargingUpdated').textContent=chargeAt?new Date(chargeAt).toLocaleTimeString('en-GB'):'—';}
  const table=document.createElement('dl');table.id='diagnosticDetails';$('#infoDialog form').append(table);
  function renderDiagnostics(){table.replaceChildren();for(const [key,item] of diagnostic){const dt=document.createElement('dt');dt.textContent=key;const dd=document.createElement('dd');dd.textContent=item.value+' · '+new Date(item.at).toLocaleTimeString('en-GB')+(Date.now()-item.at>20000?' (last received)':'');table.append(dt,dd);}}
  transport.subscribe(msg=>{const p=msg.payload || {},t=msg.topic,at=msg._observedAt || Date.now();
    if(t==='battery'&&typeof p.charging==='boolean'){wasCharging=wasCharging||charging===true;const started=p.charging===true&&charging!==true;charging=p.charging;chargeAt=at;if(started&&!msg._replay&&!seenCharging){seenCharging=true;window.setView('charging');}if(!charging)seenCharging=false;}
    if(t==='nav/progress'||t==='nav/started')lastNavTarget=typeof p.target==='string'?p.target:lastNavTarget;
    if(t==='poi/stations')populatePoints();
    if(t==='do_status'&&p.point==='HOOK'&&typeof p.state==='boolean')$('#hookState').textContent='Reported physical state: '+(p.state?'ON':'OFF');
    if(t==='wifi')diagnostic.set('Wi-Fi',{at,value:typeof p==='object'?[p.ssid,p.rssi!=null?p.rssi+' dBm':'',p.connected===false?'Disconnected':''].filter(Boolean).join(' · ')||'Feedback received':String(p)});
    if(t==='gateway/info')diagnostic.set('Gateway',{at,value:[p.gateway_id,p.version].filter(Boolean).join(' · ')||'Information received'});
    if(['battery','status','poi','fleet/job-progress'].includes(t))diagnostic.set(t,{at,value:t==='fleet/job-progress'?(p.unavailable?'Query failed':'Feedback received'):'Feedback received'});
    if(['sound/ack','relocate/success','relocate/error','do_status','ui/control/error'].includes(t)&&pending&&msg._maintenanceRequestId===pending.id){store.resolveCommand(pending.id);pending=null;$('#maintenanceFeedback').textContent=p.accepted===false||t.endsWith('/error')?'Request failed: '+(p.error||p.message||'Unknown error'):'Request acknowledged. Verify the actual robot/equipment state.';}
    renderCharge();renderMaintenance();renderDiagnostics();
  });
  setInterval(()=>{if(pending&&Date.now()-pending.at>15000){store.resolveCommand(pending.id);pending=null;$('#maintenanceFeedback').textContent='Result unknown. Inspect equipment before retrying.';}renderCharge();renderMaintenance();renderDiagnostics();},1000);
  store.subscribe(renderCharge);renderCharge();
})();
